**SPLIT**

1.   It is used to divide an array into multiple sub-arrays
2.   Arguments:array,indice,axis
3.   Array:array on which we need to split
4.   Indice:Number on which we need to divide the array
5.   Axis:X-axis(0),Y-axis
6.   It divides array into equal parts or else it will raise the error



In [3]:
import numpy as np
array_split=np.array([1,2,3,4,5,6])
result=np.split(array_split,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [4]:
result=np.split(array_split,[1,4])
print(result)

[array([1]), array([2, 3, 4]), array([5, 6])]


In [8]:
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
result=np.split(array_2d, 2,axis=0)
print(result)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [10]:
result=np.split(array_2d,2,axis=1)
print(result)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [11]:
result=np.split(array_2d,[1,3],axis=1)
print(result)

[array([[1],
       [5]]), array([[2, 3],
       [6, 7]]), array([[4],
       [8]])]


**ARRAY_SPLIT**

*   To distribute elements into unequal parts




In [12]:
array_uneven=np.array([1,2,3,4,5,6,7,8])
result=np.array_split(array_uneven,3)
print(result)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


**SHAPE**


*   It just shows the shape of the array,specificially it shows the dimension of the array
*   It will return a tuple with each element represents the size of the array



In [13]:
array_1d=np.array([1,2,3,4])
print("one dimension",array_1d.shape)

one dimension (4,)


In [14]:
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print("two dimension",array_2d.shape)

two dimension (2, 4)


**RESHAPE**


*   It changes the shape of the ndArray,though it doesn't modify any data.It will return array with a specified shape
*   Specified new shape should be compatible with the total number of elements in the new array



In [15]:
reshape_array=np.array([1,2,3,4,5,6])
result=reshape_array.reshape(6,1)
print(result)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [16]:
result=reshape_array.reshape(2,-1)
print(result)

[[1 2 3]
 [4 5 6]]


**2d and 3d Array Reshaping**

In [17]:
array_2d=np.array([[1,2,3],[4,5,6]])
print(array_2d.shape)
array_reshaped=array_2d.reshape(2,3,1)
print(array_reshaped)

(2, 3)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


**ITERATION**


*   To loop over array element-wise
*   for.....loop,nditer: To iterate over the array



In [18]:
array_1d=np.array([1,2,3,4,5,6])
for i in array_1d:
  print(i)

1
2
3
4
5
6


In [19]:
array_2d=np.array([[1,2,3],[4,5,6]])
for i in array_2d:
  for j in i:
    print(j)


1
2
3
4
5
6


In [20]:
array_3d=np.array([[[1,2,3],[4,5,6]]])
for i in array_3d:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6


In [21]:
for i in np.nditer(array_3d):
  print(i)

1
2
3
4
5
6


**JOIN**



1.   Methods to join arrays together
2.   Concatenation
3.   Stack
4.   Vstack
5.   HStack
6.   DStack



Concatenation


*   It joins two arrays along any axis. This method supports multiple arrays.
np.concatenation(array1,array2........arrayN,axis=0,out=None)
*   array1......arrayN: List of arrays which are supposed to be concatenated
*   axis: Dimension,(Rows,Column)
*   out:After concatenation,where do we want to store the results
*   Axis 1:Horizontally,Column
*   Axis 0:Vertically,Row



In [22]:
array_1=np.array([1,2,3,4])
array_2=np.array([5,6,7,8])
result=np.concatenate((array_1,array_2),axis=0)
print(result)

[1 2 3 4 5 6 7 8]


**2d Array**

In [25]:
array2d_1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
array2d_2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
result=np.concatenate((array2d_1,array2d_2),axis=1)
print(result)

[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]]


**STACK**


*   Stack also joins the array but along the new axis
*   Arrays: List of arrays to be stacked
*   Axis: Dimensions along which to stack
*   out: Optional, where to store result



In [26]:
array1 =np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])
result=np.stack((array1,array2),axis=0)
print(result)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**HSTACK**


*   HStack is used to stack arrays list horizontally(Axis 1).
*   It is equal to concatenate() function with axis=1



In [27]:
array1 =np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])
result=np.hstack((array1,array2))
print(result)

[ 1  2  3  4  5  6  7  8  9 10]


**VStack**


*   VStack is used to stack array list vertically(Axis=0).
*   It is equal to concatenate() function with axis=0



In [28]:
array1=np.array([1,2,3,4,5])
array2=np.array([5,6,7,8,9])
result=np.vstack((array1,array2))
print(result)

[[1 2 3 4 5]
 [5 6 7 8 9]]


**DSTACK**


*   DStack function will be used when we are working on 3D or 3rd Axis




In [29]:
array1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
array2=np.array([[26,27,58,39,10],[21,22,23,44,25]])
result=np.dstack((array1,array2))
print(result)

[[[ 1 26]
  [ 2 27]
  [ 3 58]
  [ 4 39]
  [ 5 10]]

 [[ 1 21]
  [ 2 22]
  [ 3 23]
  [ 4 44]
  [ 5 25]]]
