**SORT**


*   Sort is for sorting array as per specified data
*   Array:Array on which we have to perform the sorting
*   Axis:Axis along which to sort,Default=-1
*   Algorithm: Sorting algorithm:'quicksort','mergesort','heapsort','stable'
*   Order:In which order we need to sort



In [1]:
import numpy as np
array=np.array([5,5,2,1,6])
sorted_array=np.sort(array)
print(sorted_array)

[1 2 5 5 6]


In [2]:
array=np.array(['a','b','c','d'])
sorted_array=np.sort(array)
print(sorted_array)

['a' 'b' 'c' 'd']


In [3]:
array=np.array([5,5,2,3,6,7])
sorted_array=np.sort(array,kind='quicksort')
print(sorted_array)

[2 3 5 5 6 7]


In [6]:
array=np.array([[5,5,2,3,6,7],[10,11,2,3,7,2]])
sorted_array=np.sort(array,axis=1,kind='quicksort')
print(sorted_array)

[[ 2  3  5  5  6  7]
 [ 2  2  3  7 10 11]]


In [7]:
array=np.array([[5,5,2,3,6,7],[10,11,2,3,7,2]])
sorted_array=np.sort(array,axis=None,kind='quicksort')
print(sorted_array)

[ 2  2  2  3  3  5  5  6  7  7 10 11]


In [8]:
array=np.array([[5,5,2,3,6,7],[10,11,2,3,7,2]])
sorted_array=np.sort(array[1:])
print(sorted_array)

[[ 2  2  3  7 10 11]]


In [9]:
array=np.array([('A',2),('B',7)],dtype=[('letter','U1'),('number','i4')])
print(array)
sorted_numbers=np.sort(array,order='letter')
print(sorted_numbers)

[('A', 2) ('B', 7)]
[('A', 2) ('B', 7)]


**FILTER**
* To filter the elements of the array
* To filter elements based on conditions we use filters,Condition:True,False

In [10]:
array=np.array([1,2,3,4,5,6,7])
filtered_array=array[array>5]
print(filtered_array)

[6 7]


**Where**

In [13]:
array=np.array([1,2,3,4,5,6,7,8,9])
filtered_array=np.where(array>20)
print(filtered_array)

(array([], dtype=int64),)


LOGICAL METHODS FOR CONDITION
* logical_and
* logical_or

In [15]:
array=np.array([255,234,23,244,24,12])
filtered_array=array[np.logical_and(array>10,array<100)]
print(filtered_array)

[23 24 12]


**COPY**
* This method is used for copying the array into another variable.Generally for avoiding processing on original dataset

In [16]:
array=np.array([1,2,3,4,5])
array_2=np.copy(array)
array_2[1]=12
print("copied:",array_2)
print("original:",array)

copied: [ 1 12  3  4  5]
original: [1 2 3 4 5]


ARANGE
* It is to create/generate array with evenly spaced values
* Start:From where to start the values
* Stop:Until which value
* Step:Difference between each consecutive value

In [17]:
array=np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
array=np.arange(5,14)
print(array)

[ 5  6  7  8  9 10 11 12 13]


In [19]:
array=np.arange(2,100,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71
 74 77 80 83 86 89 92 95 98]


In [20]:
array=np.arange(2,100,-1)
print(array)

[]


In [21]:
array=np.arange(100,2,-1)
print(array)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3]


In [22]:
array=np.arange(0,10,1.5,dtype=float)
print(array)

[0.  1.5 3.  4.5 6.  7.5 9. ]


In [23]:
array_1=np.arange(2,10,1)
array_2=np.arange(10,2,-1)
array_2d=np.meshgrid(array_1,array_2)
print(array_2d)

[array([[2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 10, 10, 10, 10, 10, 10, 10],
       [ 9,  9,  9,  9,  9,  9,  9,  9],
       [ 8,  8,  8,  8,  8,  8,  8,  8],
       [ 7,  7,  7,  7,  7,  7,  7,  7],
       [ 6,  6,  6,  6,  6,  6,  6,  6],
       [ 5,  5,  5,  5,  5,  5,  5,  5],
       [ 4,  4,  4,  4,  4,  4,  4,  4],
       [ 3,  3,  3,  3,  3,  3,  3,  3]])]


In [24]:
array=np.arange(10)
for i in array:
  print(i)

0
1
2
3
4
5
6
7
8
9


**SEARCH**
* It is used to search elements in numpy array
* where
* searchsorted
* nonzero
* argmax
* argmin
* flatnonzero
* extract

**SearchSorted**
* Sorted_Array: 1D Array
* Value:Value for searching
* Side:'left'or'right'


In [26]:
array=np.array([1,2,3,4,5,6])
indices=np.searchsorted(array,[7])
print(indices)

[6]


**Non-Zeros**

In [27]:
array=np.array([0,0,0,0,1,1,1,1,0,1])
nonzero_array=np.nonzero(array)
print(nonzero_array)

(array([4, 5, 6, 7, 9]),)


**Argmin,Argmax**

In [29]:
array=np.argmin([2,4,4,3,3,33,213,2323])
print(array)

0


In [30]:
array=np.argmax([2,4,4,3,3,33,213,2323])
print(array)

7


**EXTRACT**
* It will return the value from the array

In [31]:
array=np.array([10,20,30,40,50,60])
result=np.extract(array>20,array)
print(result)

[30 40 50 60]


In [32]:
array_1=[24,4,4,3,33,213,2323]
print(type(array_1))
array_2=np.array([10,20,30,40,50,60])
print(type(array_2))


<class 'list'>
<class 'numpy.ndarray'>
