**NUMPY**


1.   EVERY ELEMENT IN AN ARRAY HAS A DATA TYPE
2.   IT NEEDS TO BE IN A ALLOCATED MEMORY
3.   NUMPY WORKS ON A SINGLE DATASTRUCTURE WHICH IS NDarray








**CODE EFFICIENCY**



*   Time Complexity
*   Space Complexity



In [1]:
import numpy as np
array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [2]:
print(array.dtype)

int64


In [4]:
array_new=np.array([1,2,3,4,5],dtype='S')
print(array_new)
print(array_new.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [6]:
array_4b=np.array([1,2,3,4,5],dtype='i4')
print(array_4b)
print(array_4b.dtype)

[1 2 3 4 5]
int32


**VECTORIZED OPERATIONS**

In [7]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


**BROADCASTING CONCEPT**

In [8]:
import numpy as np
a=np.array([[1],[2],[3]])
b=np.array([4,5,6])
c=a+b
print(c)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


## **FUNCTIONS IN NUMPY**
# 1.SLICE
# 2.SPLIT
# 3.JOIN
# 4.RESHAPE
# 5.SHAPE
# 6.ARRAY
# 7.ITERATOR: ndITER

SLICE

1.   Start:Index from where to start,default=0
2.   Stop:Index where to end,default=[end of the array]
3.   Step:Step is size for which need to return values.



In [9]:
import numpy as np
array_slice=np.array([1,2,3,4,5,5,6,7,7,8,9])
print(array_slice[1:4])

[2 3 4]


In [10]:
array_slice=np.array([1,2,3,4,5,5,6,7,7,8,9])
print("Default",array_slice[1:5])

Default [2 3 4 5]


In [11]:
array_slice=np.array([1,2,3,4,5,5,6,7,7,8,9])
print(array_slice[::4])

[1 5 7]


In [12]:
array_slice=np.array([1,2,3,4,5,5,6,7,7,8,9])
print(array_slice[::-1])

[9 8 7 7 6 5 5 4 3 2 1]


**2D ARRAY**

In [15]:
array=np.array([[1,2,3,4],
 [5,6,7,8],
  [3,7,8,5]])
print(array[1,2])
print(array[::-1,::-1])
print(array[1::])



7
[[5 8 7 3]
 [8 7 6 5]
 [4 3 2 1]]
[[5 6 7 8]
 [3 7 8 5]]


**3D ARRAY**

In [17]:
array_3d=np.array([[1,2,3],
 [3,4,5],
  [7,8,9],
                   [10,11,12]])
print(array_3d[0::])

[[ 1  2  3]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
